remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: "Zhiyi Wu"
author: "Zhiyi Wu"
description: "University of Maryland, College Park"

#Menu

navigation:
- {file: "zhiyi.pdf", title: "CV", icon: home}
